---
CalendarUrl: https://cloud.local.rohrmann.online/remote.php/dav/calendars/Arvid/debug3/
Degree: "MIT Winf"
MaxKWOffset: 3
MinSemester: 1
MaxSemester: 4
Timezone: Europe/Berlin
CronSchedule: "0 0,8,14,22 * * *"

ModuleWhitelist:
  - "Wissenschaftliches Arbeiten"
  - "Datenbanken"
  - "Betriebliche Anwendungssysteme"
  - "IT-Controlling"
  - "Datenkommunikation"
  - "Marketing und Strategie"
